# Generated by Django 4.0.3 on 2022-03-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='participant',
            name='password',
            field=models.CharField(default='#123', max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='username',
            field=models.CharField(default='#ilgimdar', max_length=20),
        ),
    ]
