# Generated by Django 4.0.3 on 2022-03-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datings', '0002_participant_location_participant_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='likes',
            field=models.JSONField(default={'-1': 1}, null=True),
        ),
    ]
