# Generated by Django 4.0.3 on 2022-03-24 07:23

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datings', '0003_participant_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='likes',
            field=jsonfield.fields.JSONField(default={'-1': 1}, null=True),
        ),
    ]
